# Basic
title: Zhou Wei
subtitle: My journey to data science 👧🏽
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: ta-da! welcome to my blog! 
#creator: <a href="http://onev.cat">@onevcat</a>

url: "WZHOU007-0912.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

markdown: kramdown
mathjax: true

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
#nav:
   # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: natasumushi
    # duoshuo: 
    
# Social
social:
    weibo: natasumushi
    github: WZHOU007-0912
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: WZHOU007@e.ntu.edu.sg

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
